services:
  - type: web
    name: family-organizer-server
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: family-organizer-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

  - type: web
    name: family-organizer-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          name: family-organizer-server
          type: web
          property: host
